output "installation_name" {
  description = "The name used within Earthly for the installation."
  value = var.cloud_name
}

output "account_id" {
  description = "The account ID associated with the cloud installation."
  value = data.aws_caller_identity.current.account_id
}

output "region" {
  description = "The region associated with the cloud installation."
  value = data.aws_region.current.name
}

output "security_group_id" {
  description = "The security group to apply to new satellites."
  value = aws_security_group.satellite_security_group.id
}

output "ssh_key_name" {
  description = "The SSH Key name to use when launching a satellite."
  value = aws_key_pair.satellite_ssh_key.id
}

output ssh_private_key {
  sensitive = true
  description = "The private key (if generated by module) used to SSH into the satellites."
  value = (
    var.ssh_public_key == ""
    ? ""
    : tls_private_key.satellite[0].private_key_pem
  )
}

output "allowed_subnet_ids" {
  description = "The subnets to allow launching satellites into."
  value = var.subnet
  sensitive = true
}

output "instance_profile_arn" {
  description = "The ARN of the instance profile satellites use for logging in a given cloud installation."
  value = aws_iam_instance_profile.satellite_instance_profile.arn
}

output "compute_role_arn" {
  description = "The ARN of the role Earthly will use to manage satellites on your behalf."
  value = aws_iam_role.earthly_access_role.arn
}

