output "automatic_installation" {
  description = "Surface this output in your module to enable automatic installation."
  value = {
    installation_name    = var.cloud_name
    account_id           = data.aws_caller_identity.current.account_id
    region               = data.aws_region.current.name
    security_group_id    = aws_security_group.satellite_security_group.id
    ssh_key_name         = aws_key_pair.satellite_ssh_key.id
    allowed_subnet_id    = var.subnet
    instance_profile_arn = aws_iam_instance_profile.satellite_instance_profile.arn
    compute_role_arn     = aws_iam_role.earthly_access_role.arn
  }
}

output "installation_name" {
  description = "The name used within Earthly for the installation."
  value       = var.cloud_name
}

output "security_group_id" {
  description = "The security group to apply to new satellites."
  value       = aws_security_group.satellite_security_group.id
}

output "ssh_key_name" {
  description = "The SSH Key name to use when launching a satellite."
  value       = aws_key_pair.satellite_ssh_key.id
}

output "ssh_private_key" {
  sensitive   = true
  description = "The private key (if generated by module) used to SSH into the satellites."
  value = (
    var.ssh_public_key == ""
    ? ""
    : tls_private_key.satellite[0].private_key_pem
  )
}

output "instance_profile_name" {
  description = "The name of the instance profile satellites use for logging in a given cloud installation."
  value       = aws_iam_instance_profile.satellite_instance_profile.name
}

output "compute_role_arn" {
  description = "The ARN of the role Earthly will use to manage satellites on your behalf."
  value       = aws_iam_role.earthly_access_role.arn
}
